#!/bin/bash

source "$XDG_CONFIG_HOME/colors.sh"

# Settings
bspc config border_width                  2
bspc config normal_border_color           "#555555"
bspc config focused_border_color          "$COLOR_HIGHLIGHT"
bspc config window_gap                    6
bspc config top_padding                   18
bspc config single_monocle                true
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config pointer_follows_monitor       true
bspc config focus_follows_pointer         true
bspc config click_to_focus                true
bspc config presel_feedback_color         "$COLOR_HIGHLIGHT"

# Rules

bspc rule -a '*:zathura'                  state=tiled
bspc rule -a '*:pithos'                   desktop=Ten
bspc rule -a '*:keepassx'                 state=floating
bspc rule -a '*:yad'                      state=floating
bspc rule -a '*:display'                  center=on state=floating focus=on sticky=on
bspc rule -a '*:dropterm'                 state=floating sticky=on
bspc rule -a 'Firefox:Navigator'          private=on
bspc rule -a '*:emacs'                    private=on

# Setup monitors
i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor \
        -n "$i" \
        -d {One,Two,Three,Four,Five,Six,Seven,Eight,Nine,Ten}
    let i++
done
unset i

nitrogen --restore &

bspc wm --adopt-orphans
